### ISSUE TITLE
Getting CORS error after migrating to nextzen

### ISSUE THREAD

**Issue by aharonamir** [nextzen/nextzen.js#455]
Hi, 
I am using tron map with tangram, after migrating from:
_https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.mvt_
to:
_https://tile.nextzen.org/tilezen/vector/v1/all/{z}/{x}/{y}.mvt_ (with a new api-key)
I am getting error:

> Failed to load https://tile.nextzen.org/tilezen/vector/v1/all/4/6/7.mvt?api_key=B4uoKsRxQoW3eIYgAG4TgA&: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://ipgallery-mcz.com:8244' is therefore not allowed access. The response had HTTP status code 400.

The origin url is ok and updated in the api-key origins.
Is there a change i need to make in the yaml settings or other?

**Comment by iandees** [comment]
You were getting the CORS error because the API key wasn't allowing that origin at the time of you testing it. There's some amount of caching that happens, so if you get an error once it will stick around for at least 5 minutes before any changes you make to the key show up.

When I try it now, it should work:

```
curl -vs -H "Origin: https://ipgallery-mcz.com:8244" https://tile.nextzen.org/tilezen/vector/v1/all/4/6/7.mvt\?api_key\=B4uoKsRxQoW3eIYgAG4TgA\& > /dev/null
...
HTTP/2 200
< content-type: application/x-protobuf
< content-length: 5606
...
```

**Comment by aharonamir** [comment]
Thanks, working now :smile:
